import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { toggleTheme } from "@/components/index"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(toggleTheme)
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <toggleTheme.ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </toggleTheme.ThemeProvider>
      </body>
    </html>
  );
}
