import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { toggleTheme, wrapper } from "@/components/index"
import "./globals.css"
import { cn } from "@/lib/utils"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br">
      <body className={cn(inter.className, "font-medium")}>
        <wrapper.Wrapper>
          { children }
        </wrapper.Wrapper>
      </body>
    </html>
  );
}
